Project 16 - SlideMenu
SwiftOldDriver/SwiftHomework pull request #46
Opened 2016-11-29 06:28 UTC by chenmingjia

2016-11-29 07:04 UTC, Damonvvong reviewed
- MVC 文件分层需要修改。cell 里面不应该有 model 和 NewsFactory 这种东西。
- 我觉得 NewsItem 在这个 demo 中用 struct 更佳。
- NewsFactory 的用处不是很理解。感觉可以直接作为一个 vc 的常量写在 vc 里面就好了？
- MasterTableViewCell 中的 fileprivate 应改为 private
- MasterTableViewCell 中的 awakeFromNib() 和  setSelected 等vc 中的 didReceiveMemoryWarning 、numberOfSections、没必要的函数注意删除 
- 函数下面的空行太多了。再检查一遍。官方 demo 都是没有的
- 建议 menuTransitionManager.delegate = self 这行和let menuTransitionManager = MenuTransitionManager() 写到一起

2016-11-29 07:05 UTC, Damonvvong commented
+1

2016-11-29 08:13 UTC, chenmingjia commented
@Damonvvong 
NewsFactory工厂模式主要是考虑到高层不应该依赖下层，而应该依赖于抽象，依赖倒置原则。但Demo的话不会变化,也没必要..确实可以改了

其他几条都认可...写的时候没注意到，待会改了

2016-11-29 08:15 UTC, Damonvvong commented
@chenmingjia 恩。复杂应用引入 工厂模式 可以理解。但是小 demo 可以不用这么复杂。

2016-11-29 08:27 UTC, lacklock requested changes

2016-11-29 08:27 UTC, lacklock commented on Project 16 - SlideMenu/SlideMenu/MasterTableViewController.swift
> +        if let sourceController = segue.source as? MenuTableViewController{
格式

2016-11-29 08:27 UTC, lacklock commented on Project 16 - SlideMenu/SlideMenu/MasterTableViewController.swift
> +        if let menuTableViewController = segue.destination as? MenuTableViewController{
格式

2016-11-29 08:27 UTC, lacklock commented on Project 16 - SlideMenu/SlideMenu/MenuTableViewController.swift
> +    override func numberOfSections(in tableView: UITableView) -> Int {
省略

2016-11-29 08:27 UTC, lacklock commented on Project 16 - SlideMenu/SlideMenu/MenuTableViewController.swift
> +
不要空行

2016-11-29 08:27 UTC, lacklock commented on Project 16 - SlideMenu/SlideMenu/MenuTransitionManager.swift
> +    var delegate:MenuTransitionManagerDelegate?
格式

2016-11-29 08:27 UTC, lacklock commented on Project 16 - SlideMenu/SlideMenu/MenuTransitionManager.swift
> +    var snapshot:UIView? {
格式

2016-11-29 08:27 UTC, lacklock commented
把格式都写对了再说吧。
这是对其他读代码的人的基本尊重。

2016-11-29 08:32 UTC, Martin-Lv commented
基本同意 @Damonvvong 。cell不应该依赖也不应该持有data model。如果想方便地根据dataModel更新cell，可以在UI层给cell写一个extension。

2016-11-29 09:07 UTC, chenmingjia commented
多谢大家指正，刚刚已经修改好了，以后一定多多注意 👍  :)

2016-11-29 12:17 UTC, Damonvvong commented on Project 16 - SlideMenu/SlideMenu/MasterTableViewController.swift
> +
这部分代码需要写到 cell 里面去

2016-11-29 12:17 UTC, Damonvvong commented on Project 16 - SlideMenu/SlideMenu/NewsItem.swift
> +    }
struct 不需要提供这个构造器，默认就有一个构造器

2016-11-29 12:17 UTC, Damonvvong commented
@chenmingjia 还需要再修改一下

2016-11-29 13:09 UTC, chenmingjia commented
已修正，多谢指正 @Damonvvong

2016-11-30 03:33 UTC, Damonvvong commented
@Martin-Lv @lacklock 这个我看暂时没什么问题了。你们再检查一下？

2016-11-30 05:43 UTC, Martin-Lv commented
MenuTableViewController 的 currentItem 和 MasterTableViewController 的 title 逻辑上是同一的，它们的值应该来自一个唯一的数据源。现在的做法把 MasterTableViewController 的 title 初始化硬代码写死，实际上引入了重复。建议：
1 写一个单独的数据源， menu 和主界面 title 都从这里取值。作为 demo，原来的 menu 数据源数组改为全局即可。
2 用index而不是具体的字符串维护 currentItem。这样主界面将index初始化为0即可，无需知道具体的字符串内容。

另外，建议 MasterTableViewCell 的 bind 方法写在一个单独的 fileprivate extension 中，放在 MasterTableViewController.swift 。用具体的数据类更新 cell UI 的逻辑，应该属于 controller 层，而不是 view 层。假如 view 要复用到其他页面，不应该把 NewsItem 也带过去。

昨天 review 的时候比较匆忙，第一个问题没有看出来，抱歉。

2016-11-30 14:29 UTC, lacklock commented on Project 16 - SlideMenu/SlideMenu/MasterTableViewController.swift
> +    private var newsGroup = [
这里是 let 吧？

2016-11-30 14:32 UTC, lacklock requested changes

2016-11-30 14:32 UTC, lacklock commented on Project 16 - SlideMenu/SlideMenu/MasterTableViewController.swift
> +
不需要换行

2016-11-30 14:32 UTC, lacklock commented on Project 16 - SlideMenu/SlideMenu/MenuTableViewController.swift
> +    var menuItems = ["Everyday Moments", "Popular", "Editors", "Upcoming", "Fresh", "Stock-photos", "Trending"]
let

2016-11-30 14:32 UTC, lacklock commented on Project 16 - SlideMenu/SlideMenu/MenuTableViewController.swift
> +
不要换行

2016-12-02 05:23 UTC, Martin-Lv commented
+1 我觉得可以了。

2016-12-02 06:24 UTC, merged