Project 19 Commint
SwiftOldDriver/SwiftHomework pull request #50
Opened 2016-11-30 06:20 UTC by YasinZhou

Project 19 Commint

2016-11-30 14:42 UTC, lacklock requested changes

2016-11-30 14:42 UTC, lacklock commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +    var customView:UIView!
格式！
冒号后面有空格

2016-11-30 14:42 UTC, lacklock commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +    var labelsArray: Array<UILabel> = []
[UILabel]

2016-11-30 14:42 UTC, lacklock commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +    let colorsArray: [UIColor] = [.magenta, .brown, .yellow, .red, .green, .blue, .orange]
这命名暴露了实现细节

2016-11-30 14:42 UTC, lacklock commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +        for i in 1 ... customView.subviews.count  {
for （k,v) in subviews.enumate()

2016-11-30 14:42 UTC, lacklock commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +    func endOfWork() {
重新命名

2016-11-30 14:42 UTC, lacklock commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +            for label in self.labelsArray {
用 foreach

2016-12-01 05:15 UTC, Damonvvong reviewed
- 变量和函数的权限在核查一遍。

2016-12-01 05:15 UTC, Damonvvong commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +    let dataArray = ["😂", "🤗", "😳", "😌", "😊"]
dataArray -> emojis

2016-12-01 05:15 UTC, Damonvvong commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +    var labelsArray: [UILabel] = []
var labelsArray: [UILabel] = [] -> var labels  = [UILabel]()

2016-12-01 05:15 UTC, Damonvvong commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +
空行

2016-12-01 05:15 UTC, Damonvvong commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +
空行

2016-12-01 05:15 UTC, Damonvvong commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +        loadCustomRefreshContents()
这个上下可以加个空行

2016-12-01 05:15 UTC, Damonvvong commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +    func doSomething() {
doSomething 改一下, 比如 startTimer

2016-12-01 05:15 UTC, Damonvvong commented on Project 19 - CustomPullToRefresh/CustomPullToRefresh/ViewController.swift
> +    func animateRefreshStep1() {
animateRefreshStep1 、animateRefreshStep2 这个可以换个方式？

2016-12-01 05:16 UTC, Damonvvong commented
+1

2016-12-06 07:34 UTC, merged