Project 20 - CollectionViewAnimation Finish
SwiftOldDriver/SwiftHomework pull request #59
Opened 2016-12-06 15:15 UTC by Jiar

Project 20 - CollectionViewAnimation Finish

2016-12-09 05:32 UTC, lacklock requested changes

2016-12-09 05:32 UTC, lacklock commented on Project 20 - CollectionViewAnimation/CollectionViewAnimation/ViewController.swift
> +            () -> Void in
多余的写法

2016-12-09 05:32 UTC, lacklock commented on Project 20 - CollectionViewAnimation/CollectionViewAnimation/ViewController.swift
> +        let animations: () -> Void = {
类型推断

2016-12-09 05:32 UTC, lacklock commented on Project 20 - CollectionViewAnimation/CollectionViewAnimation/ViewController.swift
> +        let completion: (Bool) -> Void = { _ in
类型推断可省略

2016-12-09 05:32 UTC, lacklock commented on Project 20 - CollectionViewAnimation/CollectionViewAnimation/ViewController.swift
> +    private struct Storyboard {
命名不好

2016-12-09 07:54 UTC, Damonvvong commented on Project 20 - CollectionViewAnimation/CollectionViewAnimation/AnimationCollectionViewCell.swift
> +    }
```
func bind(model: AnimationModel) {
         backBtn.isHidden = true
         contentImageView.image = UIImage(named: model.imagePath)
         contentTextView.isScrollEnabled = false
 }
```
extension 写在 vc 里面。

2016-12-09 07:54 UTC, Damonvvong commented on Project 20 - CollectionViewAnimation/CollectionViewAnimation/ViewController.swift
> +    private let animationModelCollection = AnimationModelCollection()
animationModelCollection？

2016-12-15 02:21 UTC, Jiar commented on Project 20 - CollectionViewAnimation/CollectionViewAnimation/AnimationCollectionViewCell.swift
> +    }
是把这个bind方法当做一个extension，放在VC里面的意思吗？

2016-12-15 02:21 UTC, Jiar commented on Project 20 - CollectionViewAnimation/CollectionViewAnimation/ViewController.swift
> +    private let animationModelCollection = AnimationModelCollection()
- -这里不太清楚用什么命名为好。。一般我是跟类名相同，开头小写。。求指教

2016-12-16 06:53 UTC, Damonvvong commented on Project 20 - CollectionViewAnimation/CollectionViewAnimation/AnimationCollectionViewCell.swift
> +    }
对。cell 的 extension 放 vc 里面。

2016-12-16 06:54 UTC, Damonvvong commented on Project 20 - CollectionViewAnimation/CollectionViewAnimation/ViewController.swift
> +    private let animationModelCollection = AnimationModelCollection()
我可能会写 animations，不过这个最好你自己想了

2016-12-16 08:06 UTC, Jiar commented
1.修改命名
2.修改必报使用方式
3.将cell的bind方法扩展到VC中

2016-12-16 08:27 UTC, merged